### ISSUE TITLE
A Question not an issue

### ISSUE THREAD

**Issue by rp1231** [brickbots/aball#3]
You've mentioned in the documentation that you've mapped the home row buttons to the mouse clicks via a layer.
Does that mean that you have to click the layer button and the mouse button at the same time(Two buttons for each mouse click).
I'm planning on setting up something similar myself, so asking out of curiosity.

Thanks

**Comment by brickbots** [comment]
Hi Hi!

Thanks for the good question here... the short answer is Yes.  The longer answer is also Yes, to use the mouse buttons I need to hold down another key to activate that layer, but it's not as bad as it might sound.  

On my keyboard the mouse layer can be activated by holding down the Z key, so I can use the pinky of my left hand to hold that down and then activate any of the mouse buttons with my thumb.  It sort of becomes muscle memory, and rather than press the Z key with each mouse click, I tend to just hold it down when using the trackball and I can click any of the mouse button keys.
